import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

import { publicShellCss, publicShellScript } from "@waypoint/ui";
import { expect, it } from "vitest";

import * as hashes from "../src/csp-hashes.ts";
import { staticCss } from "../src/pages.ts";

const sha256 = (text: string): string =>
  `'sha256-${createHash("sha256").update(text, "utf8").digest("base64")}'`;
const file = new URL("../src/csp-hashes.ts", import.meta.url);

// The reader's CSP hashes are build-time constants so no response waits on crypto. They must
// match the exact inline bodies; after changing the shell CSS or script, or the Folio tokens,
// regenerate with:
// UPDATE_CSP_HASHES=1 pnpm --filter @waypoint/reader exec vitest run tests/reader-csp-hashes.test.ts
it("matches the inline style and script bodies", () => {
  const expected = {
    shellStyleHash: sha256(publicShellCss),
    shellScriptHash: sha256(publicShellScript),
    staticStyleHash: sha256(staticCss),
  };
  const source = `// Generated by tests/reader-csp-hashes.test.ts (UPDATE_CSP_HASHES=1). Do not edit.
// SHA-256 of the exact inline <style> and <script> bodies, for the reader's hash-only CSPs.
${Object.entries(expected)
  .map(([name, value]) => `export const ${name} = "${value}";`)
  .join("\n")}
`;
  if (process.env.UPDATE_CSP_HASHES === "1" && readFileSync(file, "utf8") !== source)
    writeFileSync(file, source);
  expect({ ...hashes }).toEqual(expected);
  expect(staticCss).toMatchSnapshot();
});
