import { bindActions } from "./actions.ts";
import { bindCollection } from "./collection.ts";
import { bindCommandFallback } from "./commands.ts";
import { bindCompareMode } from "./compare-mode.ts";
import { bindFocusReturn } from "./dialogs.ts";
import { bindFrameSync } from "./frame-sync.ts";
import { bindKeysDialog } from "./keys-dialog.ts";
import { bindKeys } from "./keys.ts";
import { bindReadMarks, bindRecentMarks } from "./lastread.ts";
import { bindMenus } from "./menus.ts";
import { bindPanel } from "./panel.ts";
import { bindSearch } from "./search.ts";
import { bindShare } from "./share.ts";
import { localizeTimes } from "./time.ts";

localizeTimes();
bindCommandFallback();
bindMenus();
bindFocusReturn();
bindActions();
bindKeys();
bindKeysDialog();
bindSearch();
bindPanel();
bindRecentMarks();
bindCollection();
bindCompareMode();
bindFrameSync();
bindReadMarks();
bindShare();
