import { bindActions } from "./actions.ts";
import { bindCollection } from "./collection.ts";
import { bindCommandFallback } from "./commands.ts";
import { bindCompareMode } from "./compare-mode.ts";
import { localizeDayGroups } from "./day-groups.ts";
import { bindDetails } from "./details.ts";
import { bindFocusReturn, bindKeyboardInset } from "./dialogs.ts";
import { fillDims } from "./dims.ts";
import { bindFrameSync } from "./frame-sync.ts";
import { bindKeysDialog } from "./keys-dialog.ts";
import { bindKeys } from "./keys.ts";
import { bindReadMarks, bindRecentMarks } from "./lastread.ts";
import { bindMenus } from "./menus.ts";
import { bindPanel } from "./panel.ts";
import { bindFind, bindSearch } from "./search.ts";
import { bindShare } from "./share.ts";
import { localizeTimes } from "./time.ts";
import { showFlash } from "./toast.ts";
import { exposeVersion } from "./version.ts";

exposeVersion();
localizeTimes();
bindCommandFallback();
showFlash();
bindMenus();
bindFocusReturn();
bindKeyboardInset();
bindActions();
bindKeys();
bindKeysDialog();
bindSearch();
bindFind();
bindPanel();
localizeDayGroups();
bindRecentMarks();
bindCollection();
bindDetails();
bindCompareMode();
bindFrameSync();
fillDims();
bindReadMarks();
bindShare();
