packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@tursodatabase/database-common@0.8.2"
  - "@tursodatabase/database-darwin-arm64@0.8.2"
  - "@tursodatabase/database-linux-arm64-gnu@0.8.2"
  - "@tursodatabase/database-linux-x64-gnu@0.8.2"
  - "@tursodatabase/database-win32-x64-msvc@0.8.2"
  - "@tursodatabase/database@0.8.2"
  - "@tursodatabase/sync-common@0.8.2"
  - "@tursodatabase/sync-darwin-arm64@0.8.2"
  - "@tursodatabase/sync-linux-arm64-gnu@0.8.2"
  - "@tursodatabase/sync-linux-x64-gnu@0.8.2"
  - "@tursodatabase/sync-win32-x64-msvc@0.8.2"
  - "@tursodatabase/sync@0.8.2"
