import { bindActions } from "./client/actions.js";
import { bindCollection } from "./client/collection.js";
import { bindCommandFallback } from "./client/commands.js";
import { bindCompare } from "./client/compare.js";
import { bindFrameSync } from "./client/frame-sync.js";
import { bindKeys } from "./client/keys.js";
import { bindReadMarks, bindRecentMarks } from "./client/lastread.js";
import { bindLegacyShare } from "./client/legacy-share.js";
import { bindMenus } from "./client/menus.js";
import { bindMotion } from "./client/motion.js";
import { bindPanel } from "./client/panel.js";
import { bindSearch } from "./client/search.js";
import { localizeTimes } from "./client/time.js";

localizeTimes();
bindCommandFallback();
bindMenus();
bindMotion();
bindActions();
bindKeys();
bindSearch();
bindPanel();
bindRecentMarks();
bindCollection();
bindCompare();
bindFrameSync();
bindReadMarks();
bindLegacyShare();
