import { bindActions } from "./client/actions.ts";
import { bindCollection } from "./client/collection.ts";
import { bindCommandFallback } from "./client/commands.ts";
import { bindCompare } from "./client/compare.ts";
import { bindFocusReturn } from "./client/dialogs.ts";
import { bindFrameSync } from "./client/frame-sync.ts";
import { bindKeys } from "./client/keys.ts";
import { bindReadMarks, bindRecentMarks } from "./client/lastread.ts";
import { bindMenus } from "./client/menus.ts";
import { bindPanel } from "./client/panel.ts";
import { bindSearch } from "./client/search.ts";
import { bindShare } from "./client/share.ts";
import { localizeTimes } from "./client/time.ts";

localizeTimes();
bindCommandFallback();
bindMenus();
bindFocusReturn();
bindActions();
bindKeys();
bindSearch();
bindPanel();
bindRecentMarks();
bindCollection();
bindCompare();
bindFrameSync();
bindReadMarks();
bindShare();
