import { bindActions } from "./client/actions.js";
import { bindCollection } from "./client/collection.js";
import { bindCommandFallback } from "./client/commands.js";
import { bindCompare } from "./client/compare.js";
import { bindFocusReturn } from "./client/dialogs.js";
import { bindFrameSync } from "./client/frame-sync.js";
import { bindKeys } from "./client/keys.js";
import { bindReadMarks, bindRecentMarks } from "./client/lastread.js";
import { bindMenus } from "./client/menus.js";
import { bindPanel } from "./client/panel.js";
import { bindSearch } from "./client/search.js";
import { bindShare } from "./client/share.js";
import { localizeTimes } from "./client/time.js";

localizeTimes();
bindCommandFallback();
bindMenus();
bindFocusReturn();
bindActions();
bindKeys();
bindSearch();
bindPanel();
bindRecentMarks();
bindCollection();
bindCompare();
bindFrameSync();
bindReadMarks();
bindShare();
