// Generated by tests/reader-csp-hashes.test.ts (UPDATE_CSP_HASHES=1). Do not edit.
// SHA-256 of the exact inline <style> and <script> bodies, for the reader's hash-only CSPs.
export const shellStyleHash = "'sha256-nA3T52fF19ZFyOE+4MZPGxe41St1CZ72S+Tgzo/zQU4='";
export const shellScriptHash = "'sha256-NZHbB6mS2QAhcWNiaMeH9bNdy48bPuynqO+wWfgfcXo='";
export const staticStyleHash = "'sha256-hfiaorU1OOuoYWkyxsk83eqlGwAK1hYycGZHK/+TwHY='";
