// Generated by tests/reader-csp-hashes.test.ts (UPDATE_CSP_HASHES=1). Do not edit.
// SHA-256 of the exact inline <style> and <script> bodies, for the reader's hash-only CSPs.
export const shellStyleHash = "'sha256-peOz+48I1UaUJNAbk3MW+x/dDIhl7z5TajVcKJVPXD0='";
export const shellScriptHash = "'sha256-NRwvKYn+diukw1+lmFfA43CbMEaksBoTqT4k1LcKDeQ='";
export const staticStyleHash = "'sha256-m0zgjnOZWK9jhiR19ccGwxi/G6V58VT3/OAxXt0JDDo='";
