// Generated by tests/reader-csp-hashes.test.ts (UPDATE_CSP_HASHES=1). Do not edit.
// SHA-256 of the exact inline <style> and <script> bodies, for the reader's hash-only CSPs.
export const shellStyleHash = "'sha256-XDXTucmBn/iYjQfZHCyXSjnuMbD7aqN9CMWzxYRAdIM='";
export const shellScriptHash = "'sha256-/8fco02wSR1xAa/YHWtiko6JrF8eqxYZ8JCoB1tABuw='";
export const staticStyleHash = "'sha256-m0zgjnOZWK9jhiR19ccGwxi/G6V58VT3/OAxXt0JDDo='";
