import { readFileSync } from "node:fs";

import { defineConfig } from "tsdown";

// Waypoint's license and the notices of the third-party code the bundle inlines (generated by
// scripts/third-party-notices.ts), at the top of the bundle: the server bundle travels on its own
// (the writer serves it, the launcher caches it), so its notices travel inside it.
const notices = ["LICENSE", "THIRD_PARTY_NOTICES.md"]
  .map((file) => readFileSync(new URL(`../../${file}`, import.meta.url), "utf8").trim())
  .join("\n\n")
  .replaceAll("*/", "*\\/");

// The MCP server bundle (dist/waypoint-mcp-server.mjs): one self-contained, minified ESM file
// that the writer serves at /mcp/server.mjs and the launcher imports. Every dependency is bundled,
// so they're all devDependencies. The launcher (dist/launcher.mjs) stays on esbuild
// (esbuild.config.ts): npx caches it indefinitely, so its build must not change.
export default defineConfig({
  entry: { "waypoint-mcp-server": "src/cli.ts" },
  platform: "node",
  target: "node24",
  minify: true,
  dts: false,
  banner: `/*!\n${notices}\n*/`,
  deps: { onlyBundle: false },
  outputOptions: { codeSplitting: false },
});
