import { readFileSync } from "node:fs";
import { isBuiltin } from "node:module";

import { defineConfig } from "tsdown";

// Waypoint's license and the notices of the third-party code the bundle inlines (generated by
// scripts/third-party-notices.ts), at the top of the bundle: the server bundle travels on its own
// (the writer serves it, the launcher caches it), so its notices travel inside it.
const notices = ["LICENSE", "THIRD_PARTY_NOTICES.md"]
  .map((file) => readFileSync(new URL(`../../${file}`, import.meta.url), "utf8").trim())
  .join("\n\n")
  .replaceAll("*/", "*\\/");

// The MCP server bundle (dist/waypoint-mcp-server.mjs): one self-contained, minified ESM file
// that the writer serves at /mcp/server.mjs and the launcher imports. Every package it inlines is
// a `dependency` (so Dependabot titles their updates `fix(deps)` and they make a release) and is
// bundled anyway: tsdown would otherwise leave dependencies as imports, and the bundle may import
// only Node's built-ins. The launcher (dist/launcher.mjs) stays on esbuild (esbuild.config.ts):
// npx caches it indefinitely, so its build must not change.
export default defineConfig({
  entry: { "waypoint-mcp-server": "src/cli.ts" },
  platform: "node",
  target: "node24",
  minify: true,
  dts: false,
  banner: `/*!\n${notices}\n*/`,
  deps: { alwaysBundle: (id) => !isBuiltin(id), onlyBundle: false, onlyImport: [] },
  outputOptions: { codeSplitting: false },
});
